# Generated by Django 5.1.7 on 2025-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='unique_application_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
