# Generated by Django 5.1.7 on 2025-03-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_alter_intern_unique_application_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='intern',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_preference', to='internships.intern'),
        ),
        migrations.AddField(
            model_name='department',
            name='preference',
            field=models.TextField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='sub_department',
            field=models.CharField(default=1, max_length=40),
        ),
        migrations.AddField(
            model_name='intern',
            name='application_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='intern',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='sub_county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='internships.departmentlist'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.departmentlist'),
        ),
        migrations.CreateModel(
            name='EducationBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationBackground', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('expected_graduation', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(max_length=50)),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_background', to='internships.intern')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.FileField(upload_to='uploads/passports/')),
                ('transcript', models.FileField(upload_to='uploads/transcripts/')),
                ('CV', models.FileField(upload_to='uploads/CVs/')),
                ('recommendation', models.FileField(upload_to='uploads/rec_letters/')),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='internships.intern')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_description', models.TextField()),
                ('Intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='internships.intern')),
            ],
        ),
    ]
