# Generated by Django 5.1.7 on 2025-03-21 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_departmentlist_remove_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
