# Generated by Django 5.1.7 on 2025-03-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_intern_date_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='date_registered',
        ),
    ]
