# Generated by Django 5.1.7 on 2025-04-03 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_remove_intern_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
